config/routes.rb
Rails.application.routes.draw do
  get 'tops/main'
  post 'tops/login'
  get 'tops/logout'
  resources :tops
  resources :users
  resources :tweets
  resources :likes
  root 'tweets#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :tweet
end

app/models/tweet.rb
class Tweet < ApplicationRecord
    has_many :likes
    has_many :like_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
    has_many :likes
    has_many :like_tweets, through: :likes, source: :tweet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    tweet = Tweet.find(params[:tweet_id])
    user = User.find_by(uid: session[:login_uid])
    user.like_tweets << tweet
    redirect_to root_path
  end
  def destroy
    tweet = Tweet.find(params[:id])
    user = User.find_by(uid: session[:login_uid])
    tweet.likes.find_by(user_id: user.id).destroy
    redirect_to root_path
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def main
    render 'login'
  end
    
  def login
    if User.find_by(uid: params[:uid])
      user = User.find_by(uid: params[:uid])
      userpass = user.pass
      if BCrypt::Password.new(userpass) == params[:pass]
          session[:login_uid] = params[:uid]
          redirect_to root_path
      else
          render 'error'
      end
    else
      redirect_to users_path
    end
  end
  def logout
    session.delete(:login_uid)
    redirect_to root_path
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
    @tweets = Tweet.all
  end
  def new
    @tweet = Tweet.new
  end
  
  def create
    @tweet = Tweet.new(message: params[:tweet][:message])
    if @tweet.save
      redirect_to tweets_path
    else
      render 'new'
    end
    
  end
  
  def destroy
    tweet = Tweet.find(params[:id])
    if tweet.destroy
     redirect_to '/'
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    require 'bcrypt'
    @pass = params[:user][:pass]
    @userpass = BCrypt::Password.create(@pass)
    @user = User.new(uid: params[:user][:uid],pass: @userpass)
    if @user.save
      flash[:notice] = "1レコード追加しました"
      redirect_to users_path
    else
      render 'new'
    end
  end
  
  def destroy
    user = User.find(params[:id])
    if user.destroy
      flash[:notice] = "1レコード削除されました"
      redirect_to users_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/likes/index.html.erb
<h1>Likes#index</h1>
<p>Find me in app/views/likes/index.html.erb</p>

app/views/tops/error.html.erb
ログイン失敗です
<%= link_to '戻る', :back %>

app/views/tops/login.html.erb
<%= form_tag tops_login_path, method: :post do %>
  <%= label_tag :uid, 'ユーザーID' %>
  <%= text_field_tag :uid %>
  <%= label_tag :pass, 'パスワード' %>
  <%= password_field_tag :pass %>
  <%= submit_tag 'ログイン' %>
<% end %>

<%= link_to 'ユーザ一覧',users_path  %>

app/views/tops/login_form.html.erb
ログイン中です
<%= link_to 'ログアウト',  tops_logout_path %>

app/views/tops/main.html.erb
ログイン中です
<%= link_to 'ログアウト',  tops_logout_path %>

app/views/tweets/index.html.erb
<link href="https://fonts.googleapis.com/css2?family=Material+Icons" rel="stylesheet">
<% if session[:login_uid]%>
  <% @tweets.each do |t| %>
    <p>
      <%= t.message %><br>
      <%= link_to 'いいね', likes_path(tweet_id: t.id), method: :post %>
      <% if Like.find_by(tweet_id: t.id) %>
        <i class="material-icons">favorite</i>
      <% end %>
      <%= link_to 'いいね削除', like_path(t), method: :delete %>
      <%= link_to '削除', "/tweets/#{t.id}", method: :delete %><br>
    </p>
  <% end %>
  <%= link_to 'ツイートする',new_tweet_path %>
  <%= link_to 'ログアウト', tops_logout_path %>
  <% else %>
    <% @tweets.each do |t| %>
      <p>
        <%= t.message %><br>
      </p>
    <% end %>
   <%= link_to 'ログイン',tops_main_path %>
<% end %>

app/views/tweets/new.html.erb
<%= form_for @tweet , url: {action: :create} do |f| %>
  <%= f.label :message, 'メッセージ：' %>
  <%= f.text_field :message %>
  <%= f.submit '登録' %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
<p>
  <%= user.uid %>
  <%= user.pass %><%= link_to '削除', "/users/#{user.id}", method: :delete %><br>
</p>
<% end %>
<%= link_to 'ユーザ登録',new_user_path %>
<%= link_to 'メイン',root_path %>

app/views/users/new.html.erb
<%= form_for @user , url: {action: :create} do |f| %>
  <%= f.label :uid, 'ユーザ名：' %>
  <%= f.text_field :uid %>
  <%= f.label :pass, 'パスワード：' %>
  <%= f.text_field :pass %>
  <%= f.submit '登録' %>
<% end %>